sudo: required

language: node_js
node_js:
- "9"

services:
- docker

env:
- NODE_ENV=test

before_install:
- npm i -g @angular/cli@6.1.1 mocha karma
- ./run_chemgen_server.sh

install:
- source chemgen_docker_vars.sh && cd chemgen-next-server && npm install && mocha "./{,!(node_modules)/**/}*.test.js" --exit && cd ..
- cd chemgen-next-client && npm install && npm test ng test --watch=false


