name: image-conversion
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - openjdk
  - imagemagick
  - airflow=1.10.1
  - sshtunnel
  - flask-cors
  - jira
  - flower
  - celery
  - ipython
  - airflow-with-postgres
  - psycopg2
  - paramiko
  - dask
  - pydash
