version: "3"

services:
  arrayscan_mysql_db:
    image: mysql   # Pull mysql image from Docker Hub
    environment:   # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: arrayscan
      MYSQL_USER: arrayscan
      MYSQL_PASSWORD: password
    ports:    # Set up ports exposed for other containers to connect to
      - "3307:3306"
    volumes:
      - ./chemgen-next-dev-arrayscandb:/docker-entrypoint-initdb.d

 # chemgen_next_dev_mysql_db:
 #   image: mysql   # Pull mysql image from Docker Hub
 #   environment:   # Set up mysql database name and password
 #     MYSQL_ROOT_PASSWORD: password
 #     MYSQL_DATABASE: chemgen-next-dev
 #     MYSQL_USER: chemgen
 #     MYSQL_PASSWORD: password
 #   ports:    # Set up ports exposed for other containers to connect to
 #     - "3308:3306"
 #   volumes:  # Mount relative path source folder on host to absolute path destination folder on docker container
##       /docker-entrypoint-initdb.d will only process 1 mysql file
 #     - ./chemgen-next-dev-mysqldb:/docker-entrypoint-initdb.d

  chemgen_next_test_mysql_db:
    image: mysql   # Pull mysql image from Docker Hub
    environment:   # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chemgen-next-dev
      MYSQL_USER: chemgen
      MYSQL_PASSWORD: password
    ports:    # Set up ports exposed for other containers to connect to
      - "3308:3306"
    volumes:  # Mount relative path source folder on host to absolute path destination folder on docker container
#       /docker-entrypoint-initdb.d will only process 1 mysql file
      - ./chemgen-next-test-mysqldb:/docker-entrypoint-initdb.d

  chemgen_next_mongodb:
    hostname: chemgen_next_mongodb
    image: mongo
    environment:   # Set up mysql database name and password
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD:  password
      MONGO_INITDB_DATABASE: chemgen
    ports:    # Set up ports exposed for other containers to connect to
      - "27017:27017"
    volumes:
      - ./chemgen-next-dev-mongodb:/chemgen-next-dev-mongodb

  mongodb_seed:
    depends_on:
      - chemgen_next_mongodb
    links:
      - chemgen_next_mongodb
    build: ./chemgen-next-dev-mongodb

  wordpress_db:
     image: mysql:5.7
     restart: always
     ports:    # Set up ports exposed for other containers to connect to
        - "3309:3306"
     environment:
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: password
       MYSQL_ROOT_PASSWORD: password
     volumes:
#        - ./chemgen-next-wordpressdb:/docker-entrypoint-initdb.d
        - wordpress_db_data:/var/lib/mysql

  wordpress:
     depends_on:
       - wordpress_db
     links:
       - wordpress_db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: wordpress_db:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: password

## Using volumes will persist data
volumes:
    wordpress_db_data:
